spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://127.0.0.1:3306/cityfire?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
                username: root
                password: root
            second:  #数据源2
                url: jdbc:mysql://127.0.0.1:3306/cityfire?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
                username: root
                password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true

    mail:
    host: smtp.qq.com
    username: "自己qq@qq.com" #可以改成你的邮箱号，需要开启smtp
    password: "自己的key"
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
        mail:
            smtp:
                auth: true
                socketFactory:
                    class: javax.net.ssl.SSLSocketFactory
                    port: 465
                ssl:
                    enable: true
                starttls:
                    enable: true
                    required: true